---
settings:
  name: Azure NetApp Files
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti Azure NetApp Files
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
  - title: Inizia subito
    entries:
    - title: Scopri di più su Azure NetApp Files
      url: "/concept-azure-netapp-files.html"
    - title: Per iniziare il flusso di lavoro
      url: "/task-quick-start.html"
    - title: Configurare un'applicazione Microsoft Entra
      url: "/task-set-up-azure-ad.html"
    - title: Creare un ambiente di lavoro
      url: "/task-create-working-env.html"
  - title: USA Azure NetApp Files
    entries:
    - title: Creare e montare volumi
      url: "/task-create-volumes.html"
    - title: Gestire i volumi esistenti
      url: "/task-manage-volumes.html"
    - title: Rimuovere Azure NetApp Files
      url: "/task-remove-working-env.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
