---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes' 
summary: Scopri le novità del supporto Azure NetApp Files in BlueXP. 
---
= Novità
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le novità di Azure NetApp Files in BlueXP.



== 13 gennaio 2025



=== Funzioni di rete ora supportate in BlueXP

Quando si configura un volume in Azure NetApp Files da BlueXP , è ora possibile indicare le funzioni di rete. Ciò si allinea con le funzionalità disponibili in Azure NetApp Files nativo.



== 12 giugno 2024



=== È richiesta una nuova autorizzazione

Per gestire Azure NetApp Files Volumes da BlueXP è necessaria la seguente autorizzazione:

Microsoft.Network/virtualNetworks/subnets/read

Questa autorizzazione è necessaria per leggere una subnet di rete virtuale.

Se attualmente gestisci Azure NetApp Files da BlueXP, devi aggiungere questa autorizzazione al ruolo personalizzato associato all'applicazione Microsoft Entra precedentemente creata.

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html["Informazioni su come configurare un'applicazione Microsoft Entra e visualizzare le autorizzazioni di ruolo personalizzate"].



== 22 aprile 2024



=== I modelli di volume non sono più supportati

Non è più possibile creare un volume da un modello. Questa azione è stata associata al servizio di correzione BlueXP, che non è più disponibile.



== 11 aprile 2021



=== Supporto per i modelli di volume

Un nuovo servizio modelli di applicazione consente di impostare un modello di volume per Azure NetApp Files. Il modello dovrebbe semplificare il lavoro, in quanto alcuni parametri del volume saranno già definiti nel modello, ad esempio pool di capacità, dimensione, protocollo, VNET e subnet in cui deve risiedere il volume e altro ancora. Quando un parametro è già predefinito, è sufficiente passare al parametro di volume successivo.



=== Supporto per i modelli di volume

Un nuovo servizio modelli di applicazione consente di impostare un modello di volume per Azure NetApp Files. Il modello dovrebbe semplificare il lavoro, in quanto alcuni parametri del volume saranno già definiti nel modello, ad esempio pool di capacità, dimensione, protocollo, VNET e subnet in cui deve risiedere il volume e altro ancora. Quando un parametro è già predefinito, è sufficiente passare al parametro di volume successivo.

* https://docs.netapp.com/us-en/bluexp-remediation/concept-resource-templates.html["Scopri i modelli di applicazione e come utilizzarli nel tuo ambiente"^]
* https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-create-volumes.html["Scopri come creare un volume Azure NetApp Files da un modello"]




== 8 marzo 2021



=== Modificare dinamicamente i livelli di servizio

Ora è possibile modificare dinamicamente il livello di servizio di un volume per soddisfare le esigenze di carico di lavoro e ottimizzare i costi. Il volume viene spostato nell'altro pool di capacità senza alcun impatto sul volume.

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-manage-volumes.html#change-the-volumes-service-level["Scopri come modificare il livello di servizio di un volume"].



== 3 agosto 2020



=== Configurazione e gestione di Azure NetApp Files

Configura e gestisci Azure NetApp Files direttamente da Cloud Manager. Dopo aver creato un ambiente di lavoro Azure NetApp Files, è possibile completare le seguenti attività:

* Creare volumi NFS e SMB.
* Gestione di pool di capacità e snapshot di volumi
+
Cloud Manager consente di creare, eliminare e ripristinare snapshot di volumi. È inoltre possibile creare nuovi pool di capacità e specificarne i livelli di servizio.

* Modificare un volume modificandone le dimensioni e gestendo i tag.


La possibilità di creare e gestire Azure NetApp Files direttamente da Cloud Manager sostituisce la precedente funzionalità di migrazione dei dati.



== 5 aprile 2020



=== Migrazione dei dati a Azure NetApp Files

Ora puoi migrare i dati NFS o SMB su Azure NetApp Files direttamente da Cloud Manager. Le sincronizzazioni dei dati sono basate su BlueXP Copy and Sync.
